const { init, createPurchase, updatePrice, getInventory, reportRange, insertSupplier } = require('./db')
function numFrom(s){ const m = String(s).match(/\d+[\.,]?\d*/); return m ? Number(m[0].replace(',','.')) : 0 }
function parseDate(s){ const m = String(s).match(/(\d{1,2})[\/-](\d{1,2})(?:[\/-](\d{2,4}))?/); if (!m) return null; const d = Number(m[1]); const mo = Number(m[2]); const y = m[3]?Number(m[3]):(new Date()).getFullYear(); return `${String(y)}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}` }
function vnToAction(text){ const s = String(text||''); const low = s.toLowerCase(); if (/thu mua|mua|nhập/.test(low)) { const weight = numFrom(s.match(/(\d+[\.,]?\d*)\s*kg/i)?.[0]||''); const priceM = s.match(/giá\s*(\d+[\.,]?\d*)\s*(k|nghìn|ngàn|vnd|đ|vnđ)?/i); const priceRaw = priceM ? numFrom(priceM[1]) : numFrom(s); const scale = priceM && /k|nghìn|ngàn/i.test(priceM[2]||'') ? 1000 : 1; const price = priceRaw * scale; const tea = (s.match(/chè\s+([a-zA-Z0-9À-ỹ\s]+)/i)||[])[1]?.trim()||''; const supplier = (s.match(/từ\s+([a-zA-Z0-9À-ỹ\s]+)/i)||[])[1]?.trim()||''; const humidityM = s.match(/(ẩm|độ ẩm)\s*(\d+[\.,]?\d*)/i); const humidity = humidityM ? numFrom(humidityM[2]) : null; const date = parseDate(s) || null; return { action:'create_purchase', params:{ tea_type: tea || 'Chè xanh', supplier: supplier || '', weight, price, humidity, date } } } if (/cập nhật giá|update price/.test(low)) { const tea = (s.match(/chè\s+([a-zA-Z0-9À-ỹ\s]+)/i)||[])[1]?.trim()||''; const new_priceM = s.match(/(\d+[\.,]?\d*)\s*(k|nghìn|ngàn|vnd|đ|vnđ)?/i); const raw = new_priceM ? numFrom(new_priceM[1]) : numFrom(s); const sc = new_priceM && /k|nghìn|ngàn/i.test(new_priceM[2]||'') ? 1000 : 1; const new_price = raw * sc; return { action:'update_price', params:{ tea_type: tea || 'Chè', new_price } } } if (/tồn kho|inventory|get inventory/.test(low)) { const tea = (s.match(/chè\s+([a-zA-Z0-9À-ỹ\s]+)/i)||[])[1]?.trim()||null; return { action:'get_inventory', params: tea ? { tea_type: tea } : {} } } if (/báo cáo|report/.test(low)) { const dM = s.match(/(\d+)\s*(ngày|tuần|tháng)/i); let days = 7; if (dM) { const n = Number(dM[1]); const unit = dM[2].toLowerCase(); days = unit.includes('tuần') ? (n*7) : unit.includes('tháng') ? (n*30) : n } return { action:'report_range', params:{ days } } } if (/thêm\s+nhà cung cấp|insert supplier/.test(low)) { const name = (s.match(/(?:nhà cung cấp|supplier)\s*([a-zA-Z0-9À-ỹ\s]+)/i)||[])[1]?.trim()||''; const phone = (s.match(/(\d{9,11})/)||[])[1]||null; const address = (s.match(/địa chỉ\s+(.+)/i)||[])[1]?.trim()||null; return { action:'insert_supplier', params:{ name, phone, address } } } return { action:'unknown', params:{} }
}
async function execAction(a){ if (!a || !a.action) return { action:'unknown', params:{}, sql:[], result:{} } if (a.action==='create_purchase') { const r = await createPurchase(a.params); return { action:a.action, params:a.params, sql:r.sql, result:{ ok:true } } } if (a.action==='update_price') { const r = await updatePrice(a.params); return { action:a.action, params:a.params, sql:r.sql, result:{ ok:true } } } if (a.action==='get_inventory') { const r = await getInventory(a.params||{}); return { action:a.action, params:a.params||{}, sql:[], result:r } } if (a.action==='report_range') { const r = await reportRange(a.params||{}); return { action:a.action, params:a.params||{}, sql:[], result:r } } if (a.action==='insert_supplier') { const r = await insertSupplier(a.params||{}); return { action:a.action, params:a.params||{}, sql:[], result:r } } return { action:'unknown', params:a.params||{}, sql:[], result:{} }
}
init()
module.exports = { vnToAction, execAction }
